spring:
  application:
    name: bot-api
  mvc:
    servlet:
      path: /api
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: 5672
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}
  datasource:
    url: ${POSTGRES_DB_URL:jdbc:postgresql://localhost:5432/interactions}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver

server:
  port: 9090

ollama:
    url: ${OLLAMA_API_URL:http://localhost:11434/api/chat}
    # model: llama3.2
    model: rodolfo/novaai

logging:
  file:
    name: logs/application.log
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

management:
  server:
    port: 9091
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always
  health:
    defaults:
      enabled: false
    rabbit:
      enabled: true
    db:
      enabled: true
